networks:
   demoapi:

services:
  demoappdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=huypn@123123
    networks:
        - demoapi
  studentsupervisorapi:
    container_name: demo-api
    image: ${DOCKER_REGISTRY-}studentsupervisorapi
    build:
      context: .
      dockerfile: StudentSupervisorAPI/Dockerfile
    ports:
        - 8001:80
    depends_on:
        - demoappdb
    environment:
        - Server=demoappdb
        - Database=SchoolRules
        - pwd=huypn@123123
    networks:
        - demoapi